---
title: "Moth_KDE"
format: html
---

```{r}
rm(list = ls())
library(here) #localized file paths
library(tidyverse) #compendium of useful packages
library(janitor) #cleans data
library(rinat) #data interface for iNaturalist
library(sf) # for converting and using simple features in maps
library(rnaturalearth) #map data and functions
library(rnaturalearthdata) #map data
library(patchwork) # for stacking figures
library(sp)#For dealing with spatial data
library(adehabitatHR)# for home range estimation
library(readr)
library(lubridate)

# load + clean data
obs_moth_yearly <- read_csv(here("Semirelect_Underwing_RESEARCH_INAT.csv")) |> 
  dplyr::select(observed_on, latitude, longitude) |>
  drop_na() |>
  mutate(year = year(as.Date(observed_on))) |>
    mutate(month = month(as.Date(observed_on)),
         season = case_when(
           month %in% c(3, 4, 5) ~ "Spring",
           month %in% c(6, 7, 8) ~ "Summer",
           month %in% c(9, 10, 11) ~ "Fall",
           TRUE ~ "Winter"
         )) |>
  mutate(year_season = paste(season, year, sep = " ")) |>
  filter(year >= 2015) |> ## not enough annual data prior to 2018 for running kde
  filter(year < 2025)

# change crs
moth_sf_yearly <- st_as_sf(obs_moth_yearly, coords = c("longitude", "latitude"), crs = 4326) |>
  st_transform(5070)

north_am <- ne_countries(country = c("United States of America", "Canada"), 
                              scale = "medium", 
                              returnclass = "sf")
north_am <- st_transform(north_am, 5070)

bbox <- st_bbox(moth_sf_yearly)

# plot occurence points
ggplot() +
  geom_sf(data = north_am, fill = "gray90", color = "white", size = 0.3) +
  geom_sf(data = moth_sf_yearly, 
          alpha = 0.6, 
          size = 3, 
          color = "purple") + 
  coord_sf(xlim = c(bbox["xmin"], bbox["xmax"]),
           ylim = c(bbox["ymin"], bbox["ymax"]),
           expand = TRUE) +
  labs(title = "Semirelict Underwing Occurrence Points",
       subtitle = "Observed 2015 - 2024",
       caption = "Data: iNaturalist") +
  theme_minimal() +
  theme(
    panel.background = element_rect(fill = "aliceblue", color = NA),
    plot.title = element_text(size = 14),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank()
  )
```
# seasonal KDE
obs_moth_yearly <- read_csv(here("Semirelect_Underwing_RESEARCH_INAT.csv")) |> 
  dplyr::select(observed_on, latitude, longitude) |>
  drop_na() |>
  mutate(year = year(as.Date(observed_on))) |>
  filter(year >= 2018)

moth_seasonal <- obs_moth_yearly |>
  mutate(month = month(as.Date(observed_on)),
         season = case_when(
           month %in% c(3, 4, 5) ~ "Spring",
           month %in% c(6, 7, 8) ~ "Summer",
           month %in% c(9, 10, 11) ~ "Fall",
           TRUE ~ "Winter"
         )) |>
  filter(season %in% c("Summer", "Fall")) |>
  mutate(season = factor(season, levels = c("Summer", "Fall")))

moth_sp_season <- st_as_sf(
  moth_seasonal,
  coords = c("longitude","latitude"),
  crs = 4326
) |>
  st_transform(5070)

moth_sp_season <- as_Spatial(moth_sp_season)["season"]

# FALL 2021 -- only 3 obs
kud_season <- kernelUD(moth_sp_season, h = "href")
kde_sf_season <- st_as_sf(getverticeshr(kud_season, percent = 90)) |> 
  st_transform(4326) |> 
  rename(season = id)
kde_sf_season50 <- st_as_sf(getverticeshr(kud_season, percent = 50)) |> 
  st_transform(4326) |> 
  rename(season = id)

kde_sf_season$season <- factor(kde_sf_season$season,
                               levels = c("Summer", "Fall"))

kde_sf_season50$season <- factor(kde_sf_season50$season,
                                 levels = c("Summer", "Fall"))

north_am <- ne_countries(country = c("United States of America", "Canada"), 
                         scale = "medium", 
                         returnclass = "sf") |> 
  st_transform(4326)

bbox <- st_bbox(rbind(kde_sf_season, kde_sf_season50))

pad <- 1

#print(bbox)

season_fill <- c("#edaa09","#d7570d")

# map panels displayed in row
ggplot() +
  geom_sf(data = north_am, fill = "gray95", color = "black") +
  geom_sf(data = kde_sf_season,
          fill = adjustcolor(season_fill, alpha.f = 0.35),
          color = season_fill) +
  geom_sf(data = kde_sf_season50,
          fill = adjustcolor(season_fill, alpha.f = 0.65),
          color = season_fill) +
  facet_wrap(~season) +
  coord_sf(xlim = c(bbox["xmin"], bbox["xmax"]),
           ylim = c(bbox["ymin"], bbox["ymax"]),
           expand = TRUE) +
  theme_minimal(base_size = 12) +
  theme(axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth = 0.8),
        strip.background = element_rect(fill = "gray85", color = "black", linewidth = 0.8),
        strip.text = element_text(face = "bold", size = 9),
        legend.position = "none",
        plot.background  = element_rect(fill = "transparent", color = NA),
        panel.background = element_rect(fill = "white", color = NA))

ggsave(
  "moth_season_kernels.png",
  plot = last_plot(),
  width = 6,
  height = 4,
  dpi = 300,
  bg = "transparent"
)

# map panels displayed in column
ggplot() +
  geom_sf(data = north_am, fill = "gray95", color = "black") +
  geom_sf(data = kde_sf_season,
          fill = adjustcolor(season_fill, alpha.f = 0.35),
          color = season_fill) +
  geom_sf(data = kde_sf_season50,
          fill = adjustcolor(season_fill, alpha.f = 0.65),
          color = season_fill) +
  facet_wrap(~season, ncol = 1) +
  coord_sf(xlim = c(bbox["xmin"], bbox["xmax"]),
           ylim = c(bbox["ymin"], bbox["ymax"]),
           expand = TRUE) +
  theme_minimal(base_size = 12) +
  theme(axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth = 0.8),
        strip.background = element_rect(fill = "gray85", color = "black", linewidth = 0.8),
        strip.text = element_text(face = "bold", size = 9),
        legend.position = "none",
        plot.background  = element_rect(fill = "transparent", color = NA),
        panel.background = element_rect(fill = "white", color = NA))

ggsave(
  "moth_season_kernels_presentation.png",
  plot = last_plot(),
  width = 4,
  height = 6,
  dpi = 300,
  bg = "transparent"
)
```

